package com.fak.config;

import java.util.Map;

/**
 * A single YAML-defined constraint rule.
 * Evaluated by ConstraintEngine against the fact map produced by FactBuilder.
 */
public class ConstraintRule {
    private String id;
    private Map<String, Object> when;
    private String decision;   // ALLOW | DENY | REQUIRE_APPROVAL
    private String risk;       // critical | high | medium | low
    private String reason;

    // Getters / setters omitted for brevity — generated by Lombok in real build
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }
    public Map<String, Object> getWhen() { return when; }
    public void setWhen(Map<String, Object> when) { this.when = when; }
    public String getDecision() { return decision; }
    public void setDecision(String decision) { this.decision = decision; }
    public String getRisk() { return risk; }
    public void setRisk(String risk) { this.risk = risk; }
    public String getReason() { return reason; }
    public void setReason(String reason) { this.reason = reason; }
}
